#!/usr/bin/env bash
# CDD Compliance Report Generator
# Generates a markdown report of CDD compliance status across all open issues
# Usage: .claude/scripts/cdd-compliance-report.sh [--all | --open]

set -euo pipefail

REPO="proth1/kmflow"
MODE="${1:---open}"
OUTPUT_FILE="/Users/proth/repos/kmflow/.cdd-compliance-report.md"

echo "Generating CDD Compliance Report..."

# Fetch issues based on mode
if [[ "${MODE}" == "--all" ]]; then
    ISSUES=$(gh issue list --repo "${REPO}" --state all --limit 200 --json number,title,labels,state,createdAt,closedAt 2>/dev/null || echo "[]")
else
    ISSUES=$(gh issue list --repo "${REPO}" --state open --limit 100 --json number,title,labels,state,createdAt 2>/dev/null || echo "[]")
fi

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
TOTAL=$(echo "${ISSUES}" | python3 -c "import sys,json; print(len(json.load(sys.stdin)))" 2>/dev/null || echo "0")

# Generate report using Python for JSON parsing
python3 - "${ISSUES}" "${TIMESTAMP}" "${MODE}" "${TOTAL}" "${REPO}" > "${OUTPUT_FILE}" <<'PYTHON_SCRIPT'
import json
import sys

issues = json.loads(sys.argv[1])
timestamp = sys.argv[2]
mode = sys.argv[3]
total = sys.argv[4]
repo = sys.argv[5]

# Categorize issues
evidence_required = []
evidence_verified = []
bdd_scenarios = []
no_cdd_labels = []

for issue in issues:
    labels = [l.get("name", "") for l in issue.get("labels", [])]
    num = issue["number"]
    title = issue["title"]
    state = issue.get("state", "OPEN")

    has_evidence_required = "cdd:evidence-required" in labels
    has_verified = "cdd:verified" in labels
    has_bdd = "bdd:has-scenarios" in labels

    entry = {"number": num, "title": title, "state": state, "labels": labels}

    if has_verified:
        evidence_verified.append(entry)
    elif has_evidence_required:
        evidence_required.append(entry)
    else:
        no_cdd_labels.append(entry)

    if has_bdd:
        bdd_scenarios.append(entry)

# Generate markdown
print(f"# CDD Compliance Report")
print(f"")
print(f"**Generated**: {timestamp}")
print(f"**Repository**: {repo}")
print(f"**Scope**: {'All issues' if mode == '--all' else 'Open issues only'}")
print(f"**Total Issues**: {total}")
print(f"")
print(f"## Summary")
print(f"")
print(f"| Metric | Count |")
print(f"|--------|-------|")
print(f"| Total Issues | {total} |")
print(f"| CDD Evidence Required | {len(evidence_required)} |")
print(f"| CDD Evidence Verified | {len(evidence_verified)} |")
print(f"| BDD Scenarios Present | {len(bdd_scenarios)} |")
print(f"| No CDD Labels | {len(no_cdd_labels)} |")
compliance_rate = f"{len(evidence_verified)}/{int(total)}" if int(total) > 0 else "N/A"
print(f"| Compliance Rate | {compliance_rate} |")
print(f"")

if evidence_required:
    print(f"## Issues Awaiting Evidence")
    print(f"")
    print(f"| # | Title | Status Labels |")
    print(f"|---|-------|---------------|")
    for e in evidence_required:
        status_labels = [l for l in e["labels"] if l.startswith("status:")]
        print(f"| #{e['number']} | {e['title'][:60]} | {', '.join(status_labels)} |")
    print(f"")

if evidence_verified:
    print(f"## Issues with Verified Evidence")
    print(f"")
    print(f"| # | Title | State |")
    print(f"|---|-------|-------|")
    for e in evidence_verified[:20]:  # Limit to 20 for readability
        print(f"| #{e['number']} | {e['title'][:60]} | {e['state']} |")
    if len(evidence_verified) > 20:
        print(f"| ... | *{len(evidence_verified) - 20} more* | |")
    print(f"")

if no_cdd_labels and mode == "--open":
    print(f"## Issues Missing CDD Labels")
    print(f"")
    print(f"| # | Title | Current Labels |")
    print(f"|---|-------|----------------|")
    for e in no_cdd_labels[:20]:
        other_labels = [l for l in e["labels"] if not l.startswith("cdd:")]
        print(f"| #{e['number']} | {e['title'][:60]} | {', '.join(other_labels[:3])} |")
    if len(no_cdd_labels) > 20:
        print(f"| ... | *{len(no_cdd_labels) - 20} more* | |")
    print(f"")

print(f"---")
print(f"*Generated by CDD Compliance Report Generator*")
PYTHON_SCRIPT

echo ""
echo "Report saved to ${OUTPUT_FILE}"
