"""Roadmap HTML/PDF export service (Story #368).

Generates client-ready HTML documents from TransformationRoadmapModel,
with phase summaries, effort estimates, and best practice references.
"""

from __future__ import annotations

import html
from datetime import UTC, datetime
from typing import Any


def export_roadmap_html(
    roadmap_data: dict[str, Any],
    engagement_name: str = "Engagement",
) -> str:
    """Generate a client-ready HTML document for a roadmap.

    Args:
        roadmap_data: Serialized roadmap with phases.
        engagement_name: Name of the engagement for the title.

    Returns:
        Complete HTML document string.
    """
    phases = roadmap_data.get("phases", [])
    generated_at = roadmap_data.get("generated_at", datetime.now(UTC).isoformat())
    total_initiatives = roadmap_data.get("total_initiatives", 0)
    total_weeks = roadmap_data.get("estimated_duration_weeks", 0)

    safe_name = html.escape(engagement_name)

    phase_sections = []
    for phase in phases:
        recs_html = []
        for rec in phase.get("recommendations", []):
            deps = rec.get("depends_on", [])
            deps_str = f' <span class="dep">(Depends on: {html.escape(", ".join(deps))})</span>' if deps else ""
            recs_html.append(
                f"<tr>"
                f"<td>{html.escape(rec.get('title', 'N/A'))}</td>"
                f"<td>{html.escape(rec.get('dimension', ''))}</td>"
                f"<td>{rec.get('effort_weeks', 0)} weeks</td>"
                f"<td>{rec.get('composite_score', 0):.2f}</td>"
                f"<td>{html.escape(rec.get('rationale_summary', ''))}{deps_str}</td>"
                f"</tr>"
            )

        recs_table = "\n".join(recs_html) if recs_html else "<tr><td colspan='5'>No recommendations</td></tr>"

        phase_sections.append(
            f'<div class="phase">'
            f"<h2>Phase {phase.get('phase_number', 0)}: {html.escape(phase.get('name', ''))}</h2>"
            f'<p class="meta">Duration: ~{phase.get("duration_weeks_estimate", 0)} weeks | '
            f"{phase.get('recommendation_count', 0)} recommendations</p>"
            f"<table>"
            f"<thead><tr><th>Recommendation</th><th>Dimension</th><th>Effort</th>"
            f"<th>Priority</th><th>Rationale</th></tr></thead>"
            f"<tbody>{recs_table}</tbody>"
            f"</table>"
            f"</div>"
        )

    body = "\n".join(phase_sections)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Transformation Roadmap — {safe_name}</title>
<style>
body {{ font-family: 'Segoe UI', Arial, sans-serif; margin: 2rem; color: #333; }}
h1 {{ color: #00338D; border-bottom: 3px solid #00338D; padding-bottom: 0.5rem; }}
h2 {{ color: #0057B8; margin-top: 2rem; }}
.meta {{ color: #666; font-style: italic; }}
.summary {{ background: #f5f7fa; padding: 1rem; border-radius: 8px; margin: 1rem 0; }}
.phase {{ margin-bottom: 2rem; }}
table {{ width: 100%; border-collapse: collapse; margin-top: 0.5rem; }}
th, td {{ border: 1px solid #ddd; padding: 0.6rem; text-align: left; }}
th {{ background: #00338D; color: white; }}
tr:nth-child(even) {{ background: #f9f9f9; }}
.dep {{ color: #888; font-size: 0.85em; }}
.footer {{ margin-top: 3rem; border-top: 1px solid #ddd; padding-top: 1rem; color: #999; font-size: 0.85em; }}
</style>
</head>
<body>
<h1>Transformation Roadmap</h1>
<p class="meta">Engagement: {safe_name} | Generated: {html.escape(str(generated_at))}</p>
<div class="summary">
<strong>Total Phases:</strong> {len(phases)} |
<strong>Total Recommendations:</strong> {total_initiatives} |
<strong>Estimated Duration:</strong> {total_weeks} weeks
</div>
{body}
<div class="footer">
Generated by KMFlow Process Intelligence Platform
</div>
</body>
</html>"""
